# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: saiarea
    mvc:
        favicon:
            enabled: false
    profiles:
        active: @spring-package-profile@
    aop:
        proxy-target-class: true
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true

eureka:
    instance:
        hostname: cmssystem
    client:
        serviceUrl:
            defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
        enabled: true
        registerWithEureka: false

# ===================================================================
# cmsystem specific properties
# ===================================================================

ext: